# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = """$time$username$hostname$directory$git_branch$git_status$all"""

# Drop ugly default prompt characters
[character]
success_symbol = ''
error_symbol = ''


# ---

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname]($style) '
style = "bold yellow"
disabled = false

# Shows current directory
[directory]
truncation_symbol = '.../'
use_os_path_sep = false
format = 'at [$path]($style) '

# Shows current git branch
[git_branch]
symbol = ' '
format = '[$symbol$branch]($style)'
style = 'bold green'

# Shows current git status
[git_status]
format = ' [$all_status]($style) '
style = 'bold red'

# ---

[python]
symbol = ' '

# ---

[os]
disabled = true

[time]
format = "[$time]($style) "
style = "bold black"
disabled = false
